name: CI/CD

on:
  push:
    branches:
      - master
env:
  BUILD_FLAVOR: "Debug"
  DEPLOYGATE_OWNER: "huyhuynh88097"
  DEPLOYGATE_API_TOKEN: "3c096495-8613-444c-8b44-7e8131d06bf4"
jobs:
  setup:
    name: Setup Env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2.0.2

      - name: Bump version
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle
          versionCode: ${{github.run_number}}
          versionName: 0.${{github.run_number}}.${{github.run_id}}

  build:
    name: Build And Deploy APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: ./gradlew assemble${{ env.BUILD_FLAVOR }}

      - name: Deploy APK
        uses: jmatsu/dg-upload-app-action@v0.2
        with:
          app_owner_name: ${{ env.DEPLOYGATE_OWNER }}
          api_token: ${{ env.DEPLOYGATE_API_TOKEN }}
          app_file_path: app/build/outputs/apk/debug/app-debug.apk
