name: CICD

on:
  push:
  pull_request:
env:
  BUILD_FLAVOR: "Debug"
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        run: ./gradlew test${{ env.BUILD_FLAVOR }}
        status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              username: 'id-caller-app',
              icon_emoji: ':android_icon:',
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `【Release Information】\n${process.env.AS_WORKFLOW} on ${{ github.ref }}\n"${{ github.event.head_commit.message }}" (${process.env.AS_COMMIT})\nby ${process.env.AS_AUTHOR}`,
              }]
            }
      - name: Upload Coverage
        uses: codecov/codecov-action@v1
      - name: deploy-gate
        uses: jmatsu/dg-upload-app-action@<version>
        with:
          app_owner_name: huyhuynh88097
          api_token: ${{ secrets.DEPLOYGATE_API_TOKEN }}
          app_file_path: app/build/outputs/apk/debug/app-debug.apk
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.44.0/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/
      - name: run ktlint
        run: |
          ktlint --reporter=checkstyle,output=build/ktlint-report.xml
        continue-on-error: true
      - uses: yutailang0119/action-ktlint@v3
        with:
          report-path: build/*.xml # Support glob patterns by https://www.npmjs.com/package/@actions/glob
        continue-on-error: false # If annotations contain error of severity, action-ktlint exit 1.
