name: CI/CD

on:
  push:
    branches:
      - master
      - 'feature/*'
  pull_request:
env:
  BUILD_FLAVOR: "Debug"
  DEPLOYGATE_API_TOKEN: "3c096495-8613-444c-8b44-7e8131d06bf4"
jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              username: 'id-caller-app',
              icon_emoji: ':android_icon:',
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
              }]
            }
        if: always()
      - uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        run: ./gradlew test${{ env.BUILD_FLAVOR }}
      - name: Upload Coverage
        uses: codecov/codecov-action@v1
  ktlint:
    name: ktlint Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.44.0/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/
      - name: run ktlint
        run: |
          ktlint --reporter=checkstyle,output=build/ktlint-report.xml
        continue-on-error: true
      - uses: yutailang0119/action-ktlint@v3
        with:
          report-path: build/*.xml
        continue-on-error: false

  build:
    name: Build And Deploy APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Deploy APK
        uses: jmatsu/dg-upload-app-action@v0.2
        with:
          app_owner_name: huyhuynh88097
          api_token: ${{ env.DEPLOYGATE_API_TOKEN }}
          app_file_path: app/build/outputs/apk/release/app-release-unsigned.apk
