name: Setup Env And Build

on:
  pull_request:
  push:
    branches:
      - 'feature/*'
env:
  BUILD_FLAVOR: "Debug"
jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2.0.2

  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: ./gradlew test${{ env.BUILD_FLAVOR }}

      - name: Upload Coverage
        uses: codecov/codecov-action@v1
